#Note: Block-Place-Interval in ticks (20 ticks = 1 second)
PopUpTower:
  Block-Place-Interval: 1
  Blocks-Placed-Per-Interval: 2
  Sound: ENTITY_CHICKEN_EGG

#Note: Life-Duration in ticks (20 ticks = 1 second)
#Display-Name Placeholders: {team-name} {team-color}
Silverfish:
  Life-Duration: 400
  Display-Name:
    1: "{team-color}&l{team-name} {team-color}[■ ■ ■ ■ ■]"
    2: "{team-color}&l{team-name} {team-color}[■ ■ ■ ■ &7■]"
    3: "{team-color}&l{team-name} {team-color}[■ ■ ■ &7■ ■]"
    4: "{team-color}&l{team-name} {team-color}[■ ■ &7■ ■ ■]"
    5: "{team-color}&l{team-name} {team-color}[■ &7■ ■ ■ ■]"

Egg-Bridger:
  Max-Length: 30
  Max-Y-Variation: 18
  Sound: ENTITY_CHICKEN_EGG

Ice-Bridger:
  Block-Type: ICE
  Max-Distance: 37

