#Join our discord for support: https://discord.gg/3mJuxUW

# SPECIAL ITEM ID's
# PopUpTower - tower
# Silverfish - silverfish
# Egg-Bridger - egg-bridger
# Ice-Bridger - ice-bridger
# Custom-Command-Items - You Choose!

#Special Configs (May be removed in the future)
Dye-Tower-Ukraine: false

#Automaticlly builds you a tower
#Note: Block-Place-Interval in ticks (20 ticks = 1 second)
PopUpTower:
  Icon-Name: PopUpTower
  Icon-Type: CHEST
  Block-Type: WOOL
  Block-Place-Interval: 1
  Blocks-Placed-Per-Interval: 2
  Sound: ENTITY_CHICKEN_EGG

#Summon a Silverfish to help defend your base
#Note: Life-Duration in ticks (20 ticks = 1 second)
#Display-Name Placeholders: {team-name} {team-color}
Silverfish:
  Icon-Name: BedBug
  Icon-Type: SNOWBALL
  Life-Duration: 400
  Display-Name:
    1: "{team-color}&l{team-name} {team-color}[{sqr} {sqr} {sqr} {sqr} {sqr}]"
    2: "{team-color}&l{team-name} {team-color}[{sqr} {sqr} {sqr} {sqr} &7{sqr}]"
    3: "{team-color}&l{team-name} {team-color}[{sqr} {sqr} {sqr} &7{sqr} {sqr}]"
    4: "{team-color}&l{team-name} {team-color}[{sqr} {sqr} &7{sqr} {sqr} {sqr}]"
    5: "{team-color}&l{team-name} {team-color}[{sqr} &7{sqr} {sqr} {sqr} {sqr}]"

#Construct a bridger following the path of an egg
Egg-Bridger:
  Icon-Name: EggBridger
  Icon-Type: EGG
  Block-Type: WOOL
  Max-Length: 30
  Max-Y-Variation: 18
  Sound: ENTITY_CHICKEN_EGG

#Builds a flat bridge that only lasts for a few seconds
Ice-Bridger:
  Icon-Name: IceBridger
  Icon-Type: ICE
  Block-Type: ICE
  Max-Distance: 37

#Create as many custom Special items at you want
#Spesify is you want the command to be run as player, or as console
#Add the item to your shop.cm2 though the use of the specialID
#PlaceHolders: {player} {player-display-name} {x} {y} {z} {yaw} {pitch}
Custom-Command-Items:
  Enabled: false
  Player:
    - "specialID:material:command"
  Console:
    - "specialID:material:command"