name: Build Jar

on:
 push:
    tags:
      "v*"

jobs:
  build_dev_jars:
    name: Build jar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build jar with Maven
        run: mvn package --file pom.xml
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: Extra-Special-Items.jar
          path: |
            target/*.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            LICENSE.txt
            target/*.jar